Sprint 3/step 2
AndreSmrnv/YaP_react-burger pull request #7
Opened 2021-08-08 20:57 UTC by AndreSmrnv

2021-08-09 12:44 UTC, AygulMalikova requested changes
Хорошая работа! У вас структурированный и чистый код, разделенный на компоненты.

Но есть несколько замечаний по функционалу вашего проекта:

- Если пользователь не авторизирован и пытается создать, то его необходимо перенаправлять на страницу логина. Сейчас отображается модальное окно "что-то пошло не так" (https://prnt.sc/1loae91)
- После авторизации пользователь должен автоматически переадресовываться на тот маршрут, к которому у него не получилось получить доступ ранее.
- После обновления страницы залогиненному пользователю приходиться снова авторизироваться
- Не реализован маршрут /ingredients/:id (пункт 7. Доработка роутинга в приложении)
- При нажатии ленту заказов происходит переход на страницу профиля

Ошибка с прошлого спринта: 
- Нет удаления данных о просматриваемом в модальном окне ингредиенте при закрытии модального окна.
- дублирование типа компонента
- при первом запросе ингредиенты запрашиваются дважды (https://prnt.sc/1londf6)

Вам будет добавлена доп. итерация на их исправление. Пожалуйста, исправьте данные ошибки, а также, обратите внимание на несколько рекомендаций по улучшению вашего кода.
Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-08-09 12:44 UTC, AygulMalikova commented on src/components/sign-forgot-password/ForgotPassword.jsx
> +    console.log(form);
Можно лучше:

Перед отправкой работы, пожалуйста, убедитесь в том, что все строки кода содержащие debugger и console.log удалены.

2021-08-09 12:44 UTC, AygulMalikova commented on src/components/protected-route/index.js
> +import ProtectedRoute from "./ProtectedRoute";
Надо исправить:

Нет необходимости внутри каждой директории в компонентах создавать index.js файл. Вам достаточно иметь этот файл только в корне папки components

2021-08-09 12:44 UTC, AygulMalikova commented on src/components/ingredient-details/IngredientDetails.jsx
**Надо исправить:**
Как вы можете заметить, тип ингредиента дублируется в нескольких компонентах. Представьте, что в один момент необходимо будет добавить/удалить/изменить одно поле, и тогда это придется делать в нескольких местах. Это нарушает принцип DRY (про него можно почитать в этой статье https://habr.com/ru/post/144611/). Вам следует вынести в отдельный тип, разместить его внутри utils и импортировать внутри компонентов, где он используется.

2021-08-09 14:40 UTC, AndreSmrnv commented on src/components/sign-forgot-password/ForgotPassword.jsx
> +    console.log(form);
а можно перед сдачей комментировать пока работа не закончена окончательно? 
консоли помогают в разработке, сразу видно по какому направлению движется приложение

2021-08-11 11:16 UTC, AndreSmrnv commented on src/components/protected-route/index.js
> +import ProtectedRoute from "./ProtectedRoute";
я понимаю что это может и излишество, но мне удобно импортировать по имени папки, так через индекс вяжется сам компонент. мне кажется так основной код получается читаемей, когда пишется "from './protected-route'", а не "from './protected-route/ProtectedRoute.jsx'".
пока оставлю так, если прям критично критично, то оставьте коммент и я в дальнейшем это поправлю

2021-08-11 17:10 UTC, AndreSmrnv commented on src/components/ingredient-details/IngredientDetails.jsx
вынес в константы, спас ибо

2021-08-12 07:32 UTC, AygulMalikova commented
Ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать!
Еще раз поздравляю и желаю вам дальнейших успехов!

2021-08-12 08:04 UTC, merged